### PR TITLE
adding a couple Windows tests

### PR DESCRIPTION
**Pull request by yodurr**

### CODE REVIEW

**Comment by jonstoneman** [comment]
This seems to be missing the csproj changes.  I'm presuming you just added those two files so I'll re-add them but if there are any other csproj changes that need to be committed please submit them.

**Comment by jonstoneman** [comment]
@yodurr I also made two minor changes:
- [to handle the alarm time selectors being 24-hr on my British Windows installation](https://github.com/jonstoneman/appium-dotnet-driver/commit/f7813c49bcba48d934f3ca10270ce4022acd3fd2)
- [to give the alarm save button time to activate before it's clicked](https://github.com/jonstoneman/appium-dotnet-driver/commit/f94f6abdc24a355fb2bb7b8f93bfcc9bf38e22a3)

**Comment by jonstoneman** [comment]
@yodurr Oh, and while I didn't commit these changes I had to:
- remove "/wd/hub" from the `WindowsApplicationDriverUrl` fields
- ignore that no elements are found by `AlarmClockSession.FindElementsByName("Windows Application Driver Test Alarm")`

I've assumed that these issues were due to me using the public version of `WinAppDriver` and will be resolved by the next release of the server.

**Comment by yodurr** [comment]
Thanks!  We probably need to make that change to the WinAppDriver sample that uses the clock.  regarding wd/hub we're in an exploratory mode right now.  Probably best to remove it from the sample.  
The no alarms found is a bug if you're not seeing the alarm created.

I'll submit a pull request and double check on the alarm being created.  I'm not a big fan of how we create the alarm and wait for it to fire - will probably change it so it's set for a long time out and we just delete it in the alarms app.

**Pull request merged**
